### ISSUE TITLE
模板中的一些问题

### ISSUE THREAD

**Issue by zepinglee** [Yangruipis/SUIBEthesis#1]
1. 字号的单位有误，应该是 bp 不是 pt，另外一号是 26 bp，“1.5 倍行距”的设置也不对
2. 字体有版权问题，不应放进项目
3. 定义新的命令时的空行容易引起错误

**Comment by Yangruipis** [comment]
您好，非常感谢指正哈！因为是第一次写模板，所以还有很多要学习的地方，我会尽快改正过来的，非常感谢！

**Comment by zepinglee** [comment]
可以参考 https://github.com/latexstudio/ChinaThesis

**Comment by Yangruipis** [comment]
嗯嗯我看了一下，里面有一些还不是很明白。我先简单的按您的建议改了，最近在忙秋招，等忙完再借助你的框架有时间重写一遍吧～顺便把我们学校本科的也给写了。再次感谢！
