### ISSUE TITLE
Is there supposed to be a folder that contains fonts?

### ISSUE THREAD

**Issue by nickyang28** [Yangruipis/SUIBEthesis#3]
In zhfont.sty there is a line reading:
`
\defaultfontfeatures{Path = data/zh_CN-Adobe/, Mapping=tex-text}
`
Does it mean the fonts you used ought to be contained in the data folder?

**Comment by Yangruipis** [comment]
是的这是之前版本的方法，因为linux系统没有自带这些字体，所以我把字体文件全下好放在了文件夹里，直接调用，这样一定程度上可以做到跨平台。
但是后来因为字体不是开源的，涉及到版权问题，我就舍弃这种方法了，直接默认系统里装了这些字体。
